# Traffic Camera Dataset Configuration
path: C:\Users\Admin\Desktop\yolo_pipeline_hao\datasets\traffic
train: images/train
val: images/val
test: images/val

nc: 4
names:
  0: person
  1: bicycle
  2: car
  3: motorcycle
